#
###################################
# Site wide configuration
####################################
#
title: Attitude Extraction Advances
email:
description: A simple and awesome blog theme powered by jekyll.
url: https://nicolay-r.github.io/blog # the base hostname & protocol for your site
keywords: ["sentiment analysis", "relation extraction", "machine learning"]

#
###################################
# Jekyll configuration
####################################
#
timezone:          Europe/Paris
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /articles/:year-:month/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: technical blog
  avatar: personal-logo.png
  job: "awesome relation extraction notes"
  bio: ""
  email:
  disqus-shortname: https-nicolay-r-github-io-blog
  twitter: #nicolayr_
  facebook: #100012477589017
  google:
    plus: #username
    analytics:
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: #nicolay-r
  gitlab: #username
  stackoverflow: #username
  linkedin: #nicolay-rusnachenko-b98635193
  skype: #username
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  500px: #username
  codepen: #username
  reddit: #username
  telegram: #username
